apiVersion: v1
kind: Secret
metadata:
  name: backstage-secret
  namespace: backstage
  annotations:
    kubernetes.io/service-account.name: backstage
    kubernetes.io/service-account.namespace: backstage
type: kubernetes.io/service-account-token