apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: ghcr.io/salaboy/backstage-for-k8s:v0.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tmp
            mountPath: "/tmp/"
            readOnly: true
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-secret
            - configMapRef:
                name: backstage-cm
      volumes:
      - name: tmp
        secret:
          secretName: backstage-secret                