apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: team-d-env
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      type: development
  id: team-d-env
  parameters:
    nodes:
      count: 5
      size: small